# 
control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
joint_limits_min: [-0.3, 0,  -2.6,   -0.3, 0,  -2.6,    -0.3,  0,  -2.6,  -0.3,  0, -2.6]
joint_limits_max: [0.3,  1.4, -0.6,   0.3,  1.4, -0.6,   0.3,  1.4, -0.6, 0.3,  1.4, -0.6]


low_level:
  low_level_policy_path: "/real_experiment/B2_deploy/pre_train/b2z1/B2Z1_78000_KP360_KD5.pt"

  kps: [360, 360, 360,    360, 360, 360,  360, 360, 360,     360, 360, 360,]
  kds: [5, 5, 5,         5, 5, 5,        5, 5, 5,            5, 5, 5]

  kps_stand: [700, 700, 700,  700, 700, 700,   700, 700, 700,     700, 700, 700]
  kds_stand: [10, 10, 10,         10, 10, 10,        10, 10, 10,            10, 10, 10]

  # default_angles: [ -0.05,  0.8,  -1.5,  0.05, 0.8, -1.5, 
  #                   -0.05,  0.8,  -1.5,  0.05, 0.8, -1.5,
  #                   0.0000,  1.4800, -0.6300, -0.8400,  0.0000,  1.5700] # in real robot sequence  FR FL RR RL

  default_angles: [ -0.0,  0.8,  -1.5,  0.0, 0.8, -1.5, 
                    -0.0,  0.8,  -1.5,  0.0, 0.8, -1.5,
                    0.0000,  1.4800, -0.6300, -0.8400,  0.0000,  1.5700] # in real robot sequence  FR FL RR RL

  arm_kps: [400, 400, 400, 400, 400, 400]
  arm_kds: [40, 40, 40,  40, 40, 40]
  arm_default_angles: [0.0000,  1.4800, -0.6300, -0.8400,  0.0000,  1.5700]
  arm_default_angles_tracking: [0.0000,  0.60, -0.600, 0.100,  0.0000,  0.00, 0.00]
  # # for tracking

  arm_default_angles_initial: [0.0000,  1.4800, -0.6300, -0.8400,  0.0000,  1.5700, 0.0] # for initial

  ee_goal_center_offset: [0.2, 0, 0.7]
  arm_induced_pitch: 0.38

  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  action_scale:  [0.4, 0.45, 0.45, 0.4, 0.45, 0.45, 0.4, 0.45, 0.45, 0.4, 0.45, 0.45, 0, 0, 0, 0, 0, 0]

  cmd_scale: [2.0, 2.0, 0.25]

  num_actions: 18
  num_proprio: 71
  num_obs: 799
  history_len: 10

# FR RL RR RL


# high level controller 
high_level:
  num_proprio: 70
  num_obs: 770
  history_len: 10

  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  cmd_scale: [2.0, 2.0, 0.25]

  chair:
    arm_default_pose: [0.0, 1.9, -1.72, 0.72, 0.0, 0.0, -0.1]  # chair
    default_angles: [-0.0,  0.8,  -1.5,  0.0, 0.8, -1.5, 
                    -0.0,  0.8,  -1.5,  0.0, 0.8, -1.5,
                    0.0000,  1.9, -1.72, 0.72, 0.0, 0.0, -1.2] # in real robot sequence  FR FL RR RL
    object_height_offset: [0.0, 0.0, 0.5]

  table:
    # arm_default_pose: [0.0, 2.8, -1.15, -1.4, 0.0, 0.0, -0.1]  # table
    arm_default_pose: [0.0, 2.75, -1.15, -1.65, 0.0, 0.0, -0.1]
    default_angles: [-0.0,  0.8,  -1.5,  0.0, 0.8, -1.5, 
                      -0.0,  0.8,  -1.5,  0.0, 0.8, -1.5,
                      0.0000,  2.8, -1.15, -1.4, 0.0, 0.0, -1.2] # in real robot sequence  FR FL RR RL
    object_height_offset: [0.0, 0.6, 0.5]

  box:
    arm_default_pose: [0.0, 2.71, -0.82, -0.5, 0.0, 0.0, -0.1] # box
    default_angles: [-0.0,  0.8,  -1.5,  0.0, 0.8, -1.5, 
                      -0.0,  0.8,  -1.5,  0.0, 0.8, -1.5,
                      0.0000,  2.9, -1.4, -0.0, 0.0, 0.0, -1.2] # in real robot sequence  FR FL RR RL
    object_height_offset: [0.0, 0.3, 0.1]                                          

  action_scale: [0.5,  0.5,  0.5, 
                 0.1,  0.05, 0.05, 
                 0.05, 0.05, 0.05]
    
  num_actions: 9  # 3 base (x, y, yaw) + 6 joints angles 
  action_clip: [0.6,  0.0,  0.6, 
                0.1,  0.05, 0.05, 
                0.05, 0.05, 0.05]

  high_level_policy_path: "/real_experiment/B2_deploy/pre_train/object/physical_policy_vel_002.pt"


